osx_image: xcode9.4

dist: trusty # needs Ubuntu Trusty
# Note: if you switch to sudo: false, you'll need to launch chrome with --no-sandbox.
# See https://github.com/travis-ci/travis-ci/issues/8836
sudo: required

language: node_js
node_js: '12'

branches:
  only:
    - master
  tags: 
    - /^v.*$/
    #- all

# tags:
#   only:
#     - /^v[0-9]+.[0-9]+.[0-9]+$/

os:
  - linux
  - osx

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  yarn: true
  directories:
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

addons:
  chrome: stable # have Travis install chrome stable.

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install yarn; fi
  - yarn

script:
  # - echo "Unit Tests"
  # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then xvfb-run yarn test; else yarn test; fi

  # - echo "E2E Tests"
  # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then xvfb-run yarn test:electron; else yarn test:electron; fi

  - echo "Deploy linux version to GitHub"
  - if [[ "$TRAVIS_BRANCH" == "master" ]] && [[ "$TRAVIS_OS_NAME" == "linux" ]]; then yarn release:linux; fi

  - echo "Deploy windows version to GitHub"
  - if [[ "$TRAVIS_BRANCH" == "master" ]] && [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yarn release:win; fi

  - echo "Deploy mac version to GitHub"
  - if [[ "$TRAVIS_BRANCH" == "master" ]] && [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yarn release:mac; fi

before_cache:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then rm -rf $HOME/.cache/electron-builder/wine; fi

# deploy:
#   provider: releases
#   api_key: $GH_TOKEN
#   skip_cleanup: true
#   draft: true
#   overwrite: true
#   file_glob: true
#   file:
#     - dist/*.exe
#     - dist*.zip
#     - dist/*.dmg
#     - dist/*.snap
#     - dist/*.AppImage
#   on:
#     tags: true
#     branch: master
#   tag: latest
#   condition: '$TRAVIS_TAG =~ ^v[0-9]+.[0-9]+.[0-9]+$'